// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARP5yrDSIN1sfkr6-1AEdqC8wGM3oxM6Q',
    appId: '1:883472591171:web:862ea7c02d18c4dcc5a7f6',
    messagingSenderId: '883472591171',
    projectId: 'tailormade-e878c',
    authDomain: 'tailormade-e878c.firebaseapp.com',
    storageBucket: 'tailormade-e878c.firebasestorage.app',
    measurementId: 'G-2Z8EBECSVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVTOMbuO6s6Snm9IiZd4w3-zmViAWHd-Q',
    appId: '1:883472591171:android:8374c17f0d5ade9cc5a7f6',
    messagingSenderId: '883472591171',
    projectId: 'tailormade-e878c',
    storageBucket: 'tailormade-e878c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQiaC53UcvXOsBxuR2dAt5taqtJPV3d-8',
    appId: '1:883472591171:ios:e3dba151cdf822dac5a7f6',
    messagingSenderId: '883472591171',
    projectId: 'tailormade-e878c',
    storageBucket: 'tailormade-e878c.firebasestorage.app',
    androidClientId: '883472591171-8jpnfh25e2o4shl50t8n9re4noolq975.apps.googleusercontent.com',
    iosClientId: '883472591171-ml4k5cgtid9l523d2mbn2lkp7mviihq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tailormade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARP5yrDSIN1sfkr6-1AEdqC8wGM3oxM6Q',
    appId: '1:883472591171:web:6789466b668249cec5a7f6',
    messagingSenderId: '883472591171',
    projectId: 'tailormade-e878c',
    authDomain: 'tailormade-e878c.firebaseapp.com',
    storageBucket: 'tailormade-e878c.firebasestorage.app',
    measurementId: 'G-53Z3RC4JK1',
  );

}